import os
from bs4 import BeautifulSoup

def main():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(current_dir, 'indeed.html')
    
    html_content = ''
    with open(file_path, 'r', encoding='utf-8') as file:
        html_content = file.read()
    
    soup = BeautifulSoup(html_content, 'html.parser')
    
    what_input = soup.find('input', id='text-input-what')
    print('Search input found:')
    print(what_input)
    print('-' * 30)
    
    where_input = soup.find('input', id='text-input-where')
    print('Region input found:')
    print(where_input)
    print('-' * 30)

    # Find button by navigating from where_input because the class could be generated by javascript 
    form = where_input.find_parent('form')
    search_button = form.find('button', {'type': 'submit'})
    print('Search button found:')
    print(search_button)



if __name__ == "__main__":
    main()